### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by krakowski** [ProPra16/programmierpraktikum-abschlussprojekt-team-immortalsgg#10]
Hey,

wie bereits in der Bewertung angesprochen, sind Unit-Tests zur Zeit nicht vorhanden.
Die Aufgabe diese zu erstellen wird Dir zugeteilt. Bitte bearbeite diese Aufgabe bis
spätestens **25.07.2016 23:59 Uhr** und lade Deine Änderungen hier bei Github hoch,
sodass ich sie mir anschauen kann.

Viele Grüße,
Filip

**Comment by altra102** [comment]
die tests sind hier? https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-team-immortalsgg/blob/master/src/test/java/testTddController/TDDCompilerTest.java

oder meinst du die nicht :s

**Comment by krakowski** [comment]
Hey,

doch die meinte ich. Seltsamerweise wurden sie bei mir nach einem Import in IntelliJ nicht
angezeigt. Die Aufgabe ziehe ich dann mal wieder zurück.

Viele Grüße,
Filip
